name: nerdvpn
description: Nerd VPN v6.x
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.6
  cached_network_image: ^3.4.1
  country_codes: ^3.3.0
  country_icons: ^3.0.0
  dart_ping: ^9.0.1
  dio: ^5.7.0
  easy_localization: ^3.0.7
  extended_tabs: ^4.1.0
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.6
  flutter_html: ^3.0.0-beta.2
  flutter_inapp_purchase:
    git:
      url: https://github.com/nizwar/flutter_inapp_purchase.git
      ref: "published"
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  in_app_update: ^4.2.3
  lottie: ^3.1.2
  ndialog: ^4.3.1
  openvpn_flutter: ^1.3.2
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/images/maps/"
    - "assets/icons/"
    - "assets/animations/"
    - "assets/languages/"
    - "assets/html/"
